### ISSUE TITLE
create base layout

### ISSUE THREAD

**Issue by bestchanges** [bestchanges/studyworthy#12]
- [ ] create layout.html based on bootstrap.
- [x] Add elements from screen
- [ ] make / render this layout.

**Comment by bestchanges** [comment]
let's use one of: 
https://getbootstrap.com/docs/4.0/examples/
as base for our layout.

**Comment by efedorov-dart** [comment]
Selected 
https://getbootstrap.com/docs/4.0/examples/offcanvas/

**Comment by efedorov-dart** [comment]
How things are going so far?
