### ISSUE TITLE
Создать модели связанные с курсами:

### ISSUE THREAD

**Issue by bestchanges** [bestchanges/studyworthy#4]
- Category
- Section
- Course
- Author
- Unit

сделать скрипт с тестовыми данными, чтобы все могли себе поставить их.
В тестовые данные добавить один проект Hello Python

https://github.com/bestchanges/studyworthy/wiki/Entities

**Comment by efedorov-dart** [comment]
Hello. Any news?

**Comment by aYaremchuk** [comment]
@efedorov-dart I will push changes in the evening
